name: PR Comment Listener

on:
  issue_comment:
    types: [created]

jobs:
  trigger-workflow:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Check comment
        id: action
        run: |
          comment="${{ github.event.comment.body }}"
          
          case "$comment"
          when "/test")
            echo "action=test" >> "$GITHUB_OUTPUT"
          esac

      - name: Check Organization Membership
        if: ${{ steps.action.outputs.action != '' }}
        id: check-membership
        run: |
          ORG_NAME="ClickHouse"
          USERNAME="${{ github.event.comment.user.login }}"
          MEMBERSHIP_URL="https://api.github.com/orgs/$ORG_NAME/members/$USERNAME"

          RESULT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $MEMBERSHIP_URL)

          if echo "$RESULT" | jq -e '.state == "active"'; then
            echo "User ${{ github.event.comment.user.login }} is a member of $ORG_NAME"
          else
            echo "User ${{ github.event.comment.user.login }} is not a member of $ORG_NAME, skipping"
            exit 1
          fi

      - name: Trigger e2e tests
        if: ${{ steps.action.outputs.action == 'test' }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/e2e.yml/dispatches \
            -d '{
              "ref": "${{ github.ref_name }}",
              "inputs": {}
            }'
